
-- 1. Create Profiles Table
-- This table will store user data that is safe to be publicly available.
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  role text default 'custodio' -- Default role for new users
);

-- 2. Set up Row Level Security (RLS) for Profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- 3. Create a trigger to automatically create a profile for new users.
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, role)
  values (new.id, 'custodio');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 4. Create 'reports' table
create table reports (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles, -- FK to profiles
    report_type text,
    vehicle_number text,
    latitude float,
    longitude float,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. RLS for reports
alter table reports enable row level security;

create policy "Individuals can create reports." on reports
  for insert with check (auth.uid() = user_id);

create policy "Users can view their own reports." on reports
  for select using (auth.uid() = user_id);

-- 6. Create 'messages' table
create table messages (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles, -- FK to profiles
  text text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. RLS for messages
alter table messages enable row level security;

create policy "Individuals can create messages." on messages
  for insert with check (auth.uid() = user_id);

create policy "Users can view all messages." on messages
  for select using ( auth.role() = 'authenticated' );
